# docker-compose.yml
version: '2'

services:
  mongo:
    image: mongo:5.0.15
    restart: always
    ports:
      - "27017"
    volumes:
      - ./data/db:/data/db

  app:
    build: .
    command: sh -c "npm install && npm run dev"
    ports:
      - 3000:3000
    volumes:
      - ./:/cloud-services
    environment:
      - MONGO_URL=mongodb://127.0.0.1:27017
      - DB_NAME=cloud-services
    depends_on:
      - mongo