groups:
  - name: Alerts
    rules:
      - alert: "On API - Gateway down"
        expr: up{job="api-gateway"} < 1
        for: 15s
      - alert: "On submissions - service down"
        expr: up{job="submissions"} < 1
        for: 15s
      - alert: "On targets - service down"
        expr: up{job="targets"} < 1
        for: 15s