global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout:

rule_files:
  - alert.yml

scrape_configs:
  - job_name: "api-gateway"
    static_configs:
      - targets: ["api-gateway:4242"]
  - job_name: "submissions"
    static_configs:
      - targets: ["submissions:3003"]
  - job_name: "targets"
    static_configs:
      - targets: ["targets:3001"]