name: 'CI'
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      - workflows
    paths:
      - 'src/**'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DIR_PATH: './'
    defaults:
      run:
        working-directory: ${{ env.DIR_PATH }}
    steps:
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npx rollup --config ./rollup.config.ts --configPlugin typescript