name: 'CI - Image Recognition Service'
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      - workflows
    paths:
      - 'src/imageRecognitionService/**'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  build-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup environment
        uses: actions/setup-node@v3
        with:
          node-version: 18.15
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build:apiGateway