name: 'Jest code coverage'
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      - workflows
    paths:
      - 'src/**'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup environment
        uses: actions/setup-node@v3
        with:
          node-version: 18.15
      - name: Npm install
        run: npm ci
      - name: Run Jest code coverage
        run: npm run test:coverage:ci -- --passWithNoTests