name: 'Jest testing'
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      - workflows
    paths:
      - 'src/**'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup environment
        uses: actions/setup-node@v3
        with:
          node-version: 18.15
      - name: Npm install
        run: npm ci
      - name: Run Jest tests
        env:
          MONGO_URL: "mongodb://mongo:27017"
          DB_NAME: "cloud-services"
          API_GATEWAY_URL: "http://127.0.0.1:4242"
          TARGETS_SERVICE_URL: "http://targets:3001"
          SUBMISSIONS_SERVICE_URL: http://submissions:3003"
          IMAGE_RECOGNITION_SERVICE_URL: "http://image-recognition:3004"
          AUTH_DATABASE_PATH: "mongodb://mongo:27017/auth_service"
          TARGETS_DATABASE_PATH: "mongodb://mongo:27017/targets_service"
          SUBMISSIONS_DATABASE_PATH: "mongodb://mongo:27017/submissions_service"
          MESSAGE_BROKER_URL: "amqp://rabbitmq:5672"
          JWT_USERS_SECRET: 789
          JWT_GATEWAY_SECRET: 456
          SERVICES_API_KEY: 123
          JWT_EXPIRES_IN: 10800
          IMAGGA_API_KEY: "acc_131509f9dd4b1be"
          IMAGGA_API_SECRET: "e617c2a290749739dfbc3f4a824289b6"
        run: npm run test -- --passWithNoTests